name: GitlabSync

on:
  - push
  - delete

jobs:
  sync:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-16.04
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
        target-url: ${{ secrets.TARGET_URL }}
        #target-url: https://gitlab.com/bardakelis/jobads-project.git
        #target-url: git@gitlab.com:bardakelis/jobads-project.git
        # Such as wangchucheng
        target-username: ${{ secrets.TARGET_USERNAME }}
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.TARGET_TOKEN }}
