name: GitlabSync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: |
        echo "starting the work now!"
        username=${{ secrets.TARGET_USERNAME }}
        echo "Username: $username"
        #git remote add target https://${{ secrets.TARGET_USERNAME }}:${{ secrets.TARGET_TOKEN }}@${{ secrets.TARGET_URL }}
        git remote add target https://gitlab.com/bardakelis/jobads-project.git
        git push -f --all target
        echo "Completed with code $?"
   
     
